using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Data_Structures_CSharp.Shared
{
    public class TestEngine
    {
        private readonly int SAMPLE_SIZE_UPPER_BOUND;

        private readonly int DOMAIN_UPPER_BOUND;

        private Random random;

        public int[] elements { get; set; }

        /// <summary>
        /// Default constructor.
        /// Reads supplied sample size and domain upper bounds, builds an element array and fills it with data.
        /// </summary>
        /// <param name="sample"></param>
        /// <param name="domain"></param>
        public TestEngine(int sample, int domain)
        {
            this.random = new Random();
            this.SAMPLE_SIZE_UPPER_BOUND = sample;
            this.DOMAIN_UPPER_BOUND = domain;
            buildArray();
            populateArray();
        }

        /// <summary>
        /// Initializes the element array to a random size based on the provided sample size upper bound.
        /// </summary>
        private void buildArray()
        {
            int arrSize = this.random.Next(0, SAMPLE_SIZE_UPPER_BOUND);
            this.elements = new int[arrSize];
        }

        /// <summary>
        /// Fills the element array with random positive and negative integers within the absolute value of the provided domain upper bound.
        /// </summary>
        private void populateArray()
        {
            for(int i = 0; i < this.elements.Length; i++)
            {
                this.elements[i] = generateRandomElement();
            }
        }

        /// <summary>
        /// Generates a random integer within the full positive/negative range of the provided domain upper bound.
        /// Public access to single random values can be generated by inheriting classes.
        /// </summary>
        /// <returns>Returns an integer value.</returns>
        public int generateRandomElement()
        {
            return this.random.Next((-1 * this.DOMAIN_UPPER_BOUND), this.DOMAIN_UPPER_BOUND);
        }
    }
}
